# Generated by Django 3.2.4 on 2021-06-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('pays', models.CharField(choices=[('F', 'France'), ('C', 'Canada'), ('G', 'Germany')], max_length=1)),
                ('adresse', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('create_acount', models.BooleanField(default=False)),
                ('ship_address', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkouts',
            },
        ),
    ]
