# Generated by Django 3.2.4 on 2021-06-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='create_acount',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='ship_address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
