# Generated by Django 3.2.4 on 2021-06-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210626_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pays',
            field=models.CharField(max_length=255),
        ),
    ]
