# Generated by Django 3.2.4 on 2021-06-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marque',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('article', models.ManyToManyField(blank=True, to='service.Article')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
    ]
